// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM4JvvDZtBN3tHaJ1E98DFQglo5-jAhTM',
    appId: '1:436608130655:web:bf20368c8d9f94096645ea',
    messagingSenderId: '436608130655',
    projectId: 'iha-expense-app',
    authDomain: 'iha-expense-app.firebaseapp.com',
    storageBucket: 'iha-expense-app.appspot.com',
    measurementId: 'G-LCLB9S793H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVu12WRh9535Q6t3WIkV60pQ0SoiQoD5o',
    appId: '1:436608130655:android:875320e621dbfb756645ea',
    messagingSenderId: '436608130655',
    projectId: 'iha-expense-app',
    storageBucket: 'iha-expense-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDts-NEqC3vza_d3z3FZ3joPuE3R6e5XXQ',
    appId: '1:436608130655:ios:4425777fef673ba46645ea',
    messagingSenderId: '436608130655',
    projectId: 'iha-expense-app',
    storageBucket: 'iha-expense-app.appspot.com',
    iosBundleId: 'com.okanagancollege.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDts-NEqC3vza_d3z3FZ3joPuE3R6e5XXQ',
    appId: '1:436608130655:ios:2a6058d8840de9486645ea',
    messagingSenderId: '436608130655',
    projectId: 'iha-expense-app',
    storageBucket: 'iha-expense-app.appspot.com',
    iosBundleId: 'com.okanagancollege.frontend.RunnerTests',
  );
}
